// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneioApp.Data;

#nullable disable

namespace TorneioApp.Migrations
{
    [DbContext(typeof(TorneioAppDbContext))]
    [Migration("20220322172033_AlterarStatusPartida")]
    partial class AlterarStatusPartida
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JogadorTorneio", b =>
                {
                    b.Property<Guid>("JogadoresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TorneiosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JogadoresId", "TorneiosId");

                    b.HasIndex("TorneiosId");

                    b.ToTable("JogadorTorneio");
                });

            modelBuilder.Entity("TorneioApp.Models.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PerfilChessCom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("TorneioApp.Models.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<Guid>("JogadorBrancasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorNegrasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusPartida")
                        .HasColumnType("int");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JogadorBrancasId");

                    b.HasIndex("JogadorNegrasId");

                    b.HasIndex("TorneioId");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("TorneioApp.Models.Torneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Acrescimo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Duracao")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusTorneio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Torneios");
                });

            modelBuilder.Entity("JogadorTorneio", b =>
                {
                    b.HasOne("TorneioApp.Models.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorneioApp.Models.Torneio", null)
                        .WithMany()
                        .HasForeignKey("TorneiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TorneioApp.Models.Partida", b =>
                {
                    b.HasOne("TorneioApp.Models.Jogador", "JogadorBrancas")
                        .WithMany()
                        .HasForeignKey("JogadorBrancasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorneioApp.Models.Jogador", "JogadorNegras")
                        .WithMany()
                        .HasForeignKey("JogadorNegrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorneioApp.Models.Torneio", "Torneio")
                        .WithMany("Partidas")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JogadorBrancas");

                    b.Navigation("JogadorNegras");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("TorneioApp.Models.Torneio", b =>
                {
                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
