// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneioApp.Data;

#nullable disable

namespace TorneioApp.Migrations
{
    [DbContext(typeof(TorneioAppDbContext))]
    [Migration("20220320000717_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JogadorTorneio", b =>
                {
                    b.Property<Guid>("JogadoresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TorneiosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JogadoresId", "TorneiosId");

                    b.HasIndex("TorneiosId");

                    b.ToTable("JogadorTorneio");
                });

            modelBuilder.Entity("TorneioApp.Models.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("TorneioApp.Models.Torneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Torneios");
                });

            modelBuilder.Entity("JogadorTorneio", b =>
                {
                    b.HasOne("TorneioApp.Models.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorneioApp.Models.Torneio", null)
                        .WithMany()
                        .HasForeignKey("TorneiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
